[package]
name = "amms"
version = "0.6.2"
edition = "2021"
license = "MIT"
description = "A library to interact with automated market makers across EVM chains."
readme = "README.md"
homepage = "https://github.com/darkforestry/amms-rs"
repository = "https://github.com/darkforestry/amms-rs"
keywords = ["ethereum", "amm", "mev"]
exclude = [
    "target/*",
    ".github/*",
    ".gitignore"
]

[dependencies]
anyhow = "1.0.76"
arraydeque = { version = "0.5.1", optional = true }
artemis-core = { git = "https://github.com/paradigmxyz/artemis.git", branch = "main", optional = true }
async-trait = "0.1.76"
criterion = "0.5.1"
ethers = { version = "2.0.14", default-features = true, features = ["abigen", "ws", "ipc", "rustls"] } # TODO: update this to aloy
eyre = "0.6.11"
futures = "0.3.30"
lazy_static = "1.4.0" #TODO: why do we have this
num-bigfloat = "1.7.1"
regex = "1.9.1"
ruint = "1.12.1"
serde = "1.0.176"
serde_json = "1.0.104"
thiserror = "1.0.55"
tokio = { version = "1.29.1", features = ["full"] }
tokio-stream = "0.1.15"
tracing = "0.1.40"
# TODO: publish updated crate, move to ruint
uniswap_v3_math = { git = "https://github.com/0xKitsune/uniswap-v3-math.git", branch = "main" } 
# TODO: remove unused modules when migration is completed
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "7128c53", features = [
    "contract",
    "network",
    "node-bindings",
    "providers",
    "provider-http",
    "provider-ipc",
    "provider-ws",
    "rpc-client",
    "rpc-client-ipc",
    "rpc-client-ws",
    "rpc-types-eth",
    "rpc-types-trace",
    "signers",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-wallet",
    "signer-yubihsm",
] }

[workspace.dependencies]
#TODO: use telemetry batteries, update to have prometheus battery

[features]
default = ["filters", "state-space"]
filters = []
state-space = ["arraydeque"]
artemis = ["artemis-core"]

[dev-dependencies]
tracing-subscriber = "0.3.17"
