[package]
name = "amms"
version = "0.6.2"
edition = "2021"
license = "MIT"
description = "A library to interact with automated market makers across EVM chains."
readme = "README.md"
homepage = "https://github.com/darkforestry/amms-rs"
repository = "https://github.com/darkforestry/amms-rs"
keywords = ["ethereum", "amm", "mev"]
exclude = [
    "target/*",
    ".github/*",
    ".gitignore"
]

[dependencies]
arraydeque = { version = "0.5.1", optional = true }
artemis-core = { git = "https://github.com/paradigmxyz/artemis.git", branch = "main", optional = true }
async-trait = "0.1.80"
eyre = "0.6.12"
futures = "0.3.30"
lazy_static = "1.4.0"
num-bigfloat = "1.7.1"
regex = "1.10.4"
serde = "1.0.200"
serde_json = "1.0.116"
thiserror = "1.0.59"
tokio =  { version = "1.37.0", default-features = false, features = [ "rt-multi-thread" ] }
tracing = "0.1.40"
uniswap_v3_math = { git = "https://github.com/0xKitsune/uniswap-v3-math.git", branch = "main" } 
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "2d1c40c", features = [
    "contract",
    "network",
    "providers",
    "provider-ws",
    "rpc-types-eth",
    "signers",
    "signer-wallet",
] }

[features]
default = ["filters", "state-space"]
filters = []
state-space = ["arraydeque"]
artemis = ["artemis-core"]

[dev-dependencies]
tracing-subscriber = "0.3.18"
criterion = "0.5.1"
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "2d1c40c", features = [
    "rpc-client",
] }

[[bench]]
name = "state_space"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 3
lto = true
codegen-units = 1
debug = "full"
