[profile.default]
src = "contracts/src"
out = "contracts/out"
cache_path = "contracts/cache"
libs = ["contracts/lib"]

optimizer = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
