[package]
name = "discover"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
amms = { path = "../.." }
tokio = { version = "1", features = ["rt-multi-thread"] }
